### ISSUE TITLE
Index skipping by 2's ?

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-encryption#11]
https://github.com/UBC-ECE-Sasha/PIM-encryption/blob/8de4e5fd3ff8c70b007441edd5f6882e9af9ef92/host/host.c#L62

This looks like you are initializing every 2nd item in 'buffer'. The 'index' is incremented by (16 / 8) each time. If this is the correct behaviour, please add a comment explaining why (because otherwise it looks like a bug).

**Comment by jpzg** [comment]
It wasn't a bug, but it also wasn't necessary, so I switched to a regular loop that iterates over every element.
