### ISSUE TITLE
Use a macro to represent 'block size'

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-encryption#12]
https://github.com/UBC-ECE-Sasha/PIM-encryption/blob/b66e661d6f2fbe65c3ee4a35336e79f52f0faf8b/host/pim_crypto.c#L17

You have so many macros in 'common.h' why is this one hard coded? It seems fundamental to the operation of AES, I would have guessed that this would have been the first macro.

**Comment by jpzg** [comment]
I think I hard coded that precisely because it's so fundamental - it will always be 128 bits, so it can be a magic number. But it's definitely better practice to put it in a macro, both for code clarity and in case this is ever adapted to use an algorithm with a different block size.

**Comment by jpzg** [comment]
That's actually a bug, too - length is in bytes and the block size (128) is in bits, so `dpu_AES_ecb()` rejects operations that are not a multiple of 8 blocks where it should be fine with any number of blocks.
