### ISSUE TITLE
Move to PIM-common

### ISSUE THREAD

**Issue by jnider** [UBC-ECE-Sasha/PIM-encryption#13]
https://github.com/UBC-ECE-Sasha/PIM-encryption/blob/b66e661d6f2fbe65c3ee4a35336e79f52f0faf8b/include/common.h#L23

This definitely looks like something that should be in PIM-common (and could use the MEGABYTE macro). I'm surprised the SDK doesn't have this defined somewhere?

**Comment by jpzg** [comment]
It wasn't defined anywhere that I could find in the documentation. It would be great to get it from there, but luckily it's not something that's likely to change unexpectedly, either. I'll make a pull request to add it to PIM-common.
